### ISSUE TITLE
'analyze' from another directory fails

### ISSUE THREAD

**Issue by aybe** [discimagechef/DiscImageChef#272] opened 2020-02-02 15:56 UTC
### Prerequisites

* [x] Are you running the latest version?

### Check and fill as appropriate:
* [x] I was running DiscImageChef under Windows [10]...

### Description

If you try to read a CUE in another directory, the software apparently fails to locate tracks:

```
D:\Downloads\DiscImageChef-4.5.1.1692>DiscImageChef analyze -i "C:\SCEE\WipEout (Europe) (v1.0)\WipEout (Europe) (v1.0).cue"
DiscImageChef 4.5.1.1692-1930cf95 built by dicbuilder in Release
Copyright c 2011-2018 Natalia Portillo

Image format identified by CDRWin cuesheet.

Exception trying to identify image file WipEout (Europe) (v1.0).cue
Exception: File ""WipEout (Europe) (v1.0) (Track 01).bin"" not found.
Stack trace:    at DiscImageChef.DiscImages.CdrWin.Open(IFilter imageFilter)
Unable to open image format
No error given
```

If I copy the software next to the image it works fine.

### Exact command line used:

`DiscImageChef analyze -i "C:\SCEE\WipEout (Europe) (v1.0)\WipEout (Europe) (v1.0).cue"`

### Expected behavior:

Should work no matter where image is.

### Actual behavior:

Only works when software is next to image.
    
### Output of command execution with debug output enabled
```

D:\Downloads\DiscImageChef-4.5.1.1692>DiscImageChef analyze -i "C:\SCEE\WipEout (Europe) (v1.0)\WipEout (Europe) (v1.0).cue" -d
DiscImageChef 4.5.1.1692-1930cf95 built by dicbuilder in Release
Copyright c 2011-2018 Natalia Portillo

DEBUG (Analyze command): --debug=True
DEBUG (Analyze command): --verbose=False
DEBUG (Analyze command): --input=C:\SCEE\WipEout (Europe) (v1.0)\WipEout (Europe) (v1.0).cue
DEBUG (Analyze command): --filesystems=True
DEBUG (Analyze command): --partitions=True
DEBUG (Analyze command): --encoding=
DEBUG (Format detection): Trying plugin ACT Apricot Disk Image
DEBUG (Format detection): Trying plugin Alcohol 120% Media Descriptor Structure
DEBUG (Format detection): Trying plugin Anex86 Disk Image
DEBUG (Anex86 plugin): fdihdr.unknown = 1162627398
DEBUG (Anex86 plugin): fdihdr.hddtype = 1767318048
DEBUG (Anex86 plugin): fdihdr.hdrSize = 1970226544
DEBUG (Anex86 plugin): fdihdr.dskSize = 1160257652
DEBUG (Anex86 plugin): fdihdr.bps = 1886351989
DEBUG (Anex86 plugin): fdihdr.spt = 673196389
DEBUG (Anex86 plugin): fdihdr.heads = 808333686
DEBUG (Anex86 plugin): fdihdr.cylinders = 1411915817
DEBUG (Format detection): Trying plugin Apple ][ Interleaved Disk Image
DEBUG (Format detection): Trying plugin Apple 2IMG
DEBUG (Format detection): Trying plugin Apple Disk Archival/Retrieval Tool
DEBUG (Format detection): Trying plugin Apple DiskCopy 4.2
DEBUG (Format detection): Trying plugin Apple New Disk Image Format
DEBUG (Format detection): Trying plugin Apple NIB
DEBUG (Format detection): Trying plugin Apple Universal Disk Image Format
DEBUG (Format detection): Trying plugin Basic Lisa Utility
DEBUG (Format detection): Trying plugin BlindWrite 4
DEBUG (Format detection): Trying plugin BlindWrite 5
DEBUG (Format detection): Trying plugin CDRDAO tocfile
DEBUG (Format detection): Trying plugin CDRWin cuesheet
Image format identified by CDRWin cuesheet.

DEBUG (CDRWin plugin): Found FILE at line 1
Exception trying to identify image file WipEout (Europe) (v1.0).cue
Exception: File ""WipEout (Europe) (v1.0) (Track 01).bin"" not found.
Stack trace:    at DiscImageChef.DiscImages.CdrWin.Open(IFilter imageFilter)
Unable to open image format
No error given

D:\Downloads\DiscImageChef-4.5.1.1692>
```

**Comment by claunia** [comment] 2020-02-02 16:04
It's a known bug with images consisting of two files (CDRWin, cdrdao, Alcohol). It will be fixed by 5.0.

@SilasLaspada is this a duplicate issue? If so please link and close this one.

**Comment by aybe** [comment] 2020-02-02 16:08
Alright, thank you 💯

**Comment by claunia** [comment] 2020-02-02 16:39
Duplicate of #214

**Closed by claunia** 2020-02-02 16:39 UTC
